### ISSUE TITLE
gruvbox_italicize_strings option doesn't work

### ISSUE THREAD

**Issue by delminskii** [lifepillar/vim-gruvbox8#56] opened 2023-06-04 05:53 UTC
An option `gruvbox_italicize_strings` doesn't work anymore due one of the latest commit.
`g.gruvbox_italicize_strings = 0`

![2023-06-04_08-53](https://github.com/lifepillar/vim-gruvbox8/assets/6321554/ae4e3d24-be1b-4559-bab1-3b10b69d6eb4)

**Comment by lifepillar** [comment] 2023-06-05 09:45
It does work for me. Please provide more details:

- OS?
- Vim or Neovim?
- Vim version
- GUI or terminal?
- Inside tmux/screen?
- `echo &t_Co`
- `echo &t_ZH`

**Comment by lifepillar** [comment] 2023-06-05 09:53
Also, please test with this minimal `vimrc` (save somewhere as `vimrc_minimal`):

```vim
set nocompatible
filetype on
filetype plugin on
filetype indent on
syntax on
set backupdir=~/.vim/tmp/backup
set directory=~/.vim/tmp/swap
if !has('nvim')
  set viminfo+=n~/.vim/viminfo
endif

let g:gruvbox_italicize_strings = 0
set background=light
colorscheme gruvbox8
```

Run `vim -i NONE -N -u vimrc_minimal`. Replace `vim` with `nvim` if you are using the latter.

**Comment by ljden** [comment] 2023-06-06 04:08
Also just ran into this - probably an issue from somewhere else as the minimal config file works as expected

Setup:
* Ubuntu 22.04
* neovim 0.9.0
* gnome-terminal and bash
* `echo &t_Co` && `echo &t_ZH` commands not found

**Comment by ljden** [comment] 2023-06-06 05:36
bit more digging, looks like the issue is that neovim in terminal does not ignore the value of `gui=italic` and gruvbox8 is only disabling italics with `cterm=NONE`
```
:verbose highlight String
String         xxx ctermfg=142 gui=italic guifg=#b8bb26
        Last set from ~/.local/share/nvim/site/pack/packer/start/vim-gruvbox8/colors/gruvbox8.vim line 1254
```
https://github.com/lifepillar/vim-gruvbox8/blob/master/colors/gruvbox8.vim#LL1252-L1255
Commenting out line 1254, `String` is set on line 809 
https://github.com/lifepillar/vim-gruvbox8/blob/master/colors/gruvbox8.vim#LL809
Commenting out line 809, `String` is set on line 175
https://github.com/lifepillar/vim-gruvbox8/blob/master/colors/gruvbox8.vim#LL175

**Comment by ljden** [comment] 2023-06-06 05:57
Found it! `gui` highlight attributes are used in neovim if [`termguicolours`](https://neovim.io/doc/user/options.html#'tgc') is set 
A possible fix for this is changing line 196 to be
```diff
-  if has('gui_running')
+  if has('gui_running') || (has('nvim') && &tgc)
```

**Comment by lifepillar** [comment] 2023-06-06 13:33
Please switch to the `neovim` branch of this repo or download a [-neovim](https://github.com/lifepillar/vim-gruvbox8/tags) release. Feel free to reopen if there are further issues.

**Closed by lifepillar** 2023-06-06 13:33 UTC

**Comment by ljden** [comment] 2023-06-06 21:01
Thanks for the quick turn around!
