### ISSUE TITLE
Strange behaviour of left service column

### ISSUE THREAD

**Issue by timsofteng** [lifepillar/vim-gruvbox8#43] opened 2021-06-15 13:21 UTC
Hello.

neovim 0.5

I've noticed some strange colors on service column which usually used for git signs , lsp-errors and so on.

Take a look at the screenshot please:
![image](https://user-images.githubusercontent.com/51912173/122059353-36806d80-cdf5-11eb-8bc3-1bd4dad4fec2.png)

I use this plugin for git signs https://github.com/lewis6991/gitsigns.nvim but it's similar with vim-signify
![image](https://user-images.githubusercontent.com/51912173/122059660-895a2500-cdf5-11eb-87f8-8ef9c56dc289.png)

Look like it is inversion of colors.

Also please take a look at unused part of that column. Should this color be different from background?
![image](https://user-images.githubusercontent.com/51912173/122059915-c7574900-cdf5-11eb-9f33-7d1684d5da4a.png)

**Comment by lifepillar** [comment] 2021-06-15 13:37
Possibly related to a recently merged pull request: https://github.com/lifepillar/vim-gruvbox8/pull/42.

@casonadams I see that you have included some changes to otherwise transparent background colors for the sign column. Can you confirm that what the OP shows depends on those changes?

Perhaps, then, those commits should be reverted.

**Comment by timsofteng** [comment] 2021-06-15 13:53
> Possibly related to a recently merged pull request: #42.
> 
> @casonadams I see that you have included some changes to otherwise transparent background colors for the sign column. Can you confirm that what the OP shows depends on those changes?
> 
> Perhaps, then, those commits should be reverted.

Thanks for fast response.
I faced up with this issue long time ago. Just didn't open issue.

btw in with this plugin https://github.com/tanvirtin/vgit.nvim signs display correctrly

**Comment by lifepillar** [comment] 2021-06-16 05:45
Ok,I'll investigate further.

**Comment by lifepillar** [comment] 2021-06-22 18:08
I don't see anything wrong in Gruvbox 8 re this issue. In particular, the background color of the sign column is never set to yellow or green, so it's not the color scheme that sets those colors. You should check whether the plugins you are mentioning are setting those colors.

>Also please take a look at unused part of that column. Should this color be different from background?

Yes, that is by design, and I think it's just like the original Gruvbox. You may define:

```vim
hi SignColumn ctermbg=NONE guibg=NONE
```

in your `vimrc` after loading the color scheme if you want to remove the background.

**Comment by timsofteng** [comment] 2021-07-13 06:47
Got it! How about reverse colours on the first screen? May it be fixed? I mean inversion

**Comment by lifepillar** [comment] 2021-07-13 08:02
>Got it! How about reverse colours on the first screen? May it be fixed? I mean inversion

As I said, I think those are set by some plugin. You may use the `:sign` command to list the defined signs. That might give you a hint about who is defining them. For instance:

```vim
:sign place buffer=N
```

where `N` is the number of the buffer with the sign column.

**Comment by timsofteng** [comment] 2021-07-13 22:51
> > Got it! How about reverse colours on the first screen? May it be fixed? I mean inversion
> 
> As I said, I think those are set by some plugin. You may use the `:sign` command to list the defined signs. That might give you a hint about who is defining them. For instance:
> 
> ```viml
> :sign place buffer=N
> ```
> 
> where `N` is the number of the buffer with the sign column.

Hm. I've tried to figure out but  I got just this:
![image](https://user-images.githubusercontent.com/51912173/125535063-b9065ac9-d348-452d-8f40-1aeb28ac0b3c.png)

I've just noticed that inverstions is only with your gruvbox.
I've tried another gruvbox colorschemes and they are ok.
But I like your colorsceme and don't want to change it due to this small reason.

**Comment by lifepillar** [comment] 2021-07-14 10:03
Have you specified the right buffer number? Does that buffer have visible signs?

I have tried with Signify, and with a buffer that looks like this:

![signs](https://user-images.githubusercontent.com/1193314/125602325-7f896251-4b06-4dd1-aeb0-06399614557b.jpg)

I get this:

```
:sign place buffer=5

--- Signs ---                                                                                                                        
Signs for /Users/nicola/.vim/vimrc:
    line=805  id=256  name=SignifyChange  priority=10
    line=806  id=257  name=SignifyAdd  priority=10
```

With `:sign list` I can get the highlight groups associated to those signs:

```
:sign list

sign SignifyAdd text=+  linehl= texthl=SignifySignAdd
sign SignifyChange text=!  linehl= texthl=SignifySignChange                                                                          
sign SignifyChangeDelete text=!‾ linehl= texthl=SignifySignChangeDelete
sign SignifyRemoveFirstLine text=‾  linehl= texthl=SignifySignDeleteFirstLine
```

Then, I can see how those highlight groups are defined:

```
:hi SignifySignAdd
SignifySignAdd xxx links to DiffAdd

:hi SignifySignChange
SignifySignChange xxx links to DiffChange
```

So, you see “inverted” colors because those highlight groups link to `DiffAdd` and `DiffChange`, which in this color scheme are defined as follows (in the terminal):

```
:hi DiffAdd
DiffAdd        xxx term=bold cterm=reverse ctermfg=142 ctermbg=235 […]

:hi DiffChange
DiffChange     xxx term=bold cterm=reverse ctermfg=107 ctermbg=235 […]
```

You don't see “inverted” colors with other color schemes likely because they do not define `cterm=reverse` and/or they do not define a background color for those highlight groups (or they do not define those highlight groups at all).

I am not going to change `DiffAdd` and `DiffChange` in `gruvbox8`. But you may read about a possible resolution in a similar issue for Solarized 8: https://github.com/lifepillar/vim-solarized8/issues/55.

**Comment by lifepillar** [comment] 2023-06-05 10:06
Closing as Gruvbox 8 sets colors as intended. To override some highlight groups, this guide may be useful: [How to override a colorscheme?](https://github.com/vim/colorschemes/wiki/How-to-override-a-colorscheme%3F).

**Closed by lifepillar** 2023-06-05 10:06 UTC
